apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-api
  namespace: default
spec:
  selector:
    matchLabels:
      app: laravel-api
  template:
    metadata:
      labels:
        app: laravel-api
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      initContainers:
        - name: check-db-ready
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z laravel-api-mysql 3306; do echo waiting for MySQL; sleep 2; done;",
            ]
      containers:
        - name: laravel-api
          image: diegodevopscp2.azurecr.io/aks-app/app-aks:casopractico2 # Obtenemos la imagen que hemos creado
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: laravel-api-secret # Utilizamos los secrets previamente creados
          ports:
            - containerPort: 80
              name: http
