apiVersion: v1
kind: Service
metadata:
  name: laravel-api
  namespace: default
spec:
  selector:
    app: laravel-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer # Exponemos el servicio a través de un balanceador de carga
