apiVersion: v1
kind: Service
metadata:
  name: laravel-api-mysql
  namespace: default
  labels:
    app: laravel-api
spec:
  ports:
    - port: 3306
  selector:
    app: laravel-api
    tier: mysql
  clusterIP: None
