apiVersion: v1
kind: Service
metadata:
  name: laravel-api-mysql
  namespace: default
  labels:
    app: laravel-api
spec:
  ports:
    - port: 3306
  selector:
    app: laravel-api
    tier: mysql
  clusterIP: None # No necesitamos un ClusterIP para el servicio de MySQL, ya que no necesitamos acceder a él desde fuera del clúster
