apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-api-mysql
  namespace: default
  labels:
    app: laravel-api
spec:
  selector:
    matchLabels:
      app: laravel-api
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: laravel-api
        tier: mysql
    spec:
      containers:
        - image: mysql:8.0
          name: mysql
          envFrom:
            - secretRef:
                name: mysql-secret
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
