apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: dGVzdA== # valor de prueba, cambiar por un valor seguro
  MYSQL_HOST: dGVzdA== # valor de prueba, cambiar por un valor seguro
  MYSQL_DATABASE: dGVzdA== # valor de prueba, cambiar por un valor seguro
  MYSQL_USER: dGVzdA== # valor de prueba, cambiar por un valor seguro
  MYSQL_PASSWORD: dGVzdA== # valor de prueba, cambiar por un valor seguro
