apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: dGVzdA==
  MYSQL_HOST: dGVzdA==
  MYSQL_DATABASE: dGVzdA==
  MYSQL_USER: dGVzdA==
  MYSQL_PASSWORD: dGVzdA==
