- name: Configurar la VM con Nginx y Podman
  hosts: vm_azure
  vars_files:
      - secrets.yml
  become: true
  become_method: sudo
  roles:
      - vm

- name: Configurar AKS
  hosts: local
  vars_files:
      - secrets.yml
  become: false
  roles:
      - aks